author: Ben Nuttall
modified: '2020-03-09T10:54:10'
published: '2020-03-07T16:20:56'
slug: the-mysterious-case-of-the-unexplained-downloads-spike
tags:
- flask
- sentry
- stats
title: The mysterious case of the unexplained downloads spike
