templates_dir: templates
csv_dir: csv

build:
  posts_dir: posts
  static_dir: static
  output_dir: www

logs:
  logs_dir: apache2
  pattern: "blog.piwheels.org-access*"

analytics:
  output_dir: analytics
  base_url: https://blog.piwheels.org
