csv_dir: csv
templates_dir: templates
base_url: https://blog.piwheels.org

build:
  posts_dir: posts
  static_dir: static
  output_dir: www

logs:
  logs_dir: apache2
  pattern: "blog.piwheels.org-access*"

analytics:
  output_dir: analytics
  manifest_path: www/manifest.json