modified: '2019-06-27T17:55:55'
published: '2019-06-24T07:30:22'
slug: raspberry-pi-4-and-raspbian-buster
tags:
- python-3-7
- raspberry-pi-4
- raspbian-buster
title: Raspberry Pi 4 and Raspbian Buster
