author: Ben Nuttall
modified: '2020-09-25T10:35:09'
published: '2020-09-25T10:35:08'
slug: requires-python-support-new-project-page-layout-and-a-new-json-api
tags:
- updates
title: Requires-Python support, new project page layout and a new JSON API
